import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/providers/theme-provider";

import localFont from "next/font/local";

import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Medi-AI",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    title: "Medi-AI",
    description: "AI-powered medical platform",
    url: "https://yourwebsite.com",
    images: [
      {
        url: "/favicon.ico",
        width: 1200,
        height: 630,
        alt: "Medi-AI",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <link rel="icon" href="/favicon.ico" sizes="any" />
          <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
          <meta property="og:title" content="Medi-AI" />
          <meta
            property="og:description"
            content="AI-powered medical platform"
          />
          <meta property="og:image" content="/favicon.ico" />
          <meta property="og:url" content="https://yourwebsite.com" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
